#!/bin/bash
set -e
name=toolbox-${USER}
image='dlneintr/toolbox:latest'

old=$(kubectl get pod --field-selector=status.phase!=Running -l name=${name} --output='jsonpath={.items..metadata.name}')
if [ "${old}" != "" ]; then
  kubectl delete pod --grace-period=0 ${name}
fi

kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: ${name}
  labels:
    app: ktoolbox
    name: ${name}
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  containers:
  - image: ${image}
    imagePullPolicy: Always
    name: toolbox
    lifecycle:
      preStop:
        exec:
          command: ['/usr/bin/curl', '-X', 'POST', 'http://127.0.0.1:15020/quitquitquit']
EOF

command="exec /bin/bash"
if [ "$2" != "" ]; then
  command="$@"
fi

kubectl wait --for condition=Ready pod/${name} && kubectl exec -it -c toolbox ${name} /bin/bash -- -c "${command}"
