#!/bin/bash
set -e

name=toolbox-${USER}
image='dlneintr/toolbox:latest'

max_idle_mins="180"
namespace=""

function usage() {
  cat <<EOF
Usage:
  $0 [-i max_idle_mins] [-n namespace] [cmd...]
    -h                 Display this help message.
    -n NAMESPACE       Use given namespace instead of context default.
    -i MAX_IDLE_MINS   Max idle time in minutes before exiting. ${max_idle_mins} mins by default.
EOF
}

while getopts ":hi:n:" opt; do
  case ${opt} in
    h )
      usage
      exit 0
      ;;
    n )
      namespace="$OPTARG"
      ;;
    i )
      max_idle_mins="$OPTARG"
      ;;
    \? )
      echo "Invalid Option: -$OPTARG" 1>&2
      usage
      exit 1
    ;;
  esac
done
shift $((OPTIND -1))

old=$(kubectl get pod --namespace "${namespace}" --field-selector=status.phase!=Running -l name=${name} --output='jsonpath={.items..metadata.name}')
if [ "${old}" != "" ]; then
  kubectl delete pod --namespace "${namespace}" --grace-period=0 ${name}
fi

timestamp=$(date)

kubectl apply --namespace "${namespace}" --record -f - >>/dev/null <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: ${name}
  labels:
    app: ktoolbox
    name: ${name}
  annotations:
    toolbox/active.hostname: "${HOSTNAME}"
    toolbox/active.timestamp: "${timestamp}"
    toolbox/active.username: "${USER}"
    toolbox/max.idle.minutes: "${max_idle_mins}"
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  containers:
  - image: ${image}
    imagePullPolicy: Always
    name: toolbox
    lifecycle:
      preStop:
        exec:
          command: ['/usr/bin/curl', '-X', 'POST', 'http://127.0.0.1:15020/quitquitquit']
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
      readOnly: true
    env:
    - name: MAX_IDLE_MINS
      valueFrom:
        fieldRef:
          fieldPath: metadata.annotations['toolbox/max.idle.minutes']
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: K8S_HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: K8S_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: K8S_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: K8S_POD_SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
EOF

command="exec /bin/bash"
if [[ -n "$1" ]]; then
  command="$*"
fi

kubectl wait --namespace "${namespace}" --for condition=Ready pod/${name} >>/dev/null
kubectl exec --namespace "${namespace}" -it -c toolbox ${name} /bin/bash -- -c "${command}"
